# Generated by Django 3.1.7 on 2021-05-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='description',
        ),
    ]
