# Generated by Django 3.1.7 on 2021-04-05 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210402_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.module'),
        ),
    ]
