# Generated by Django 3.1.7 on 2021-04-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20210405_1331'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='module_title',
            new_name='title',
        ),
    ]
