# Generated by Django 3.1.7 on 2021-04-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20210405_1403'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
    ]
