# Generated by Django 3.1.7 on 2021-04-29 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20210428_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='profile',
        ),
    ]
