# Generated by Django 3.1.7 on 2021-05-05 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('quizzes', '0003_remove_studentanswer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='courses.course'),
        ),
    ]
