# Generated by Django 3.1.7 on 2021-05-05 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20210505_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='quantity',
            new_name='attempts_number',
        ),
    ]
