# Generated by Django 3.1.7 on 2021-05-10 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_auto_20210508_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='attempts_number',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
